//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biquette {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Biquette.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez un nom.
        /// </summary>
        public static string choose_name {
            get {
                return ResourceManager.GetString("choose_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copier dans le presse-papier.
        /// </summary>
        public static string copy_to_clipboard {
            get {
                return ResourceManager.GetString("copy_to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créez une partie en cliquant sur le bouton ci-dessous, copiez-collez ensuite le lien et envoyez-le à vos ami·es !.
        /// </summary>
        public static string create_a_game_message {
            get {
                return ResourceManager.GetString("create_a_game_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer une partie.
        /// </summary>
        public static string create_game {
            get {
                return ResourceManager.GetString("create_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En jeu.
        /// </summary>
        public static string in_game {
            get {
                return ResourceManager.GetString("in_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Biquette.
        /// </summary>
        public static string little_goat {
            get {
                return ResourceManager.GetString("little_goat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre nom ne doit pas être vide.
        /// </summary>
        public static string name_cant_be_empty {
            get {
                return ResourceManager.GetString("name_cant_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pas d&apos;autres joueurs pour le moment....
        /// </summary>
        public static string no_other_players_yet {
            get {
                return ResourceManager.GetString("no_other_players_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jouer.
        /// </summary>
        public static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Joueurs.
        /// </summary>
        public static string players {
            get {
                return ResourceManager.GetString("players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commencer une nouvelle partie.
        /// </summary>
        public static string start_new_serie {
            get {
                return ResourceManager.GetString("start_new_serie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Démarrer la partie.
        /// </summary>
        public static string start_the_game {
            get {
                return ResourceManager.GetString("start_the_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le célèbre jeu de mémoire !.
        /// </summary>
        public static string the_famous_game_of_little_goat {
            get {
                return ResourceManager.GetString("the_famous_game_of_little_goat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour commencer.
        /// </summary>
        public static string to_start {
            get {
                return ResourceManager.GetString("to_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à URL à envoyer aux autres joueurs.
        /// </summary>
        public static string url_to_share {
            get {
                return ResourceManager.GetString("url_to_share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider.
        /// </summary>
        public static string validate {
            get {
                return ResourceManager.GetString("validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous ne pouvez pas jouer seul·e !.
        /// </summary>
        public static string you_cant_play_alone {
            get {
                return ResourceManager.GetString("you_cant_play_alone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre nom.
        /// </summary>
        public static string your_name {
            get {
                return ResourceManager.GetString("your_name", resourceCulture);
            }
        }
    }
}
