//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biquette.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameCard
    {
        public int Symbol { get; set; }
        public int Value { get; set; }
        public int GameId { get; set; }
        public string PlayerId { get; set; }
        public int Position { get; set; }
        public bool IsCover { get; set; }
        public string FileName { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
    }
}
