//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleGoat {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LittleGoat.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chat.
        /// </summary>
        public static string chat {
            get {
                return ResourceManager.GetString("chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez un nom.
        /// </summary>
        public static string choose_name {
            get {
                return ResourceManager.GetString("choose_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cliquez ici pour voir tout l&apos;historique des messages.
        /// </summary>
        public static string click_to_see_older_messages {
            get {
                return ResourceManager.GetString("click_to_see_older_messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copier.
        /// </summary>
        public static string copy_to_clipboard {
            get {
                return ResourceManager.GetString("copy_to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créez une partie en cliquant sur le bouton ci-dessous, copiez-collez ensuite le lien et envoyez-le à vos ami·es !.
        /// </summary>
        public static string create_a_game_message {
            get {
                return ResourceManager.GetString("create_a_game_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer une partie.
        /// </summary>
        public static string create_game {
            get {
                return ResourceManager.GetString("create_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet email est déjà utilisé. S&apos;il s&apos;agit du votre, n&apos;hésitez pas à utiliser la fonction de récupération de compte..
        /// </summary>
        public static string email_already_used {
            get {
                return ResourceManager.GetString("email_already_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;email n&apos;est pas obligatoire, mais il servira si jamais vous changez de téléphone/PC, pour retrouver votre nom et vos scores.
        /// </summary>
        public static string email_not_mandatory {
            get {
                return ResourceManager.GetString("email_not_mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accueil.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En jeu.
        /// </summary>
        public static string in_game {
            get {
                return ResourceManager.GetString("in_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet email n&apos;est pas valide.
        /// </summary>
        public static string invalid_email {
            get {
                return ResourceManager.GetString("invalid_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reprendre la dernière partie.
        /// </summary>
        public static string join_last_game {
            get {
                return ResourceManager.GetString("join_last_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Biquette.
        /// </summary>
        public static string little_goat {
            get {
                return ResourceManager.GetString("little_goat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mémorisez vos cartes !.
        /// </summary>
        public static string memorize_your_cards {
            get {
                return ResourceManager.GetString("memorize_your_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce nom est déjà utilisé.
        /// </summary>
        public static string name_already_used {
            get {
                return ResourceManager.GetString("name_already_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre nom ne doit pas être vide.
        /// </summary>
        public static string name_cant_be_empty {
            get {
                return ResourceManager.GetString("name_cant_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A {0} de jouer !.
        /// </summary>
        public static string next_to_play_1 {
            get {
                return ResourceManager.GetString("next_to_play_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pas d&apos;autres joueurs pour le moment....
        /// </summary>
        public static string no_other_players_yet {
            get {
                return ResourceManager.GetString("no_other_players_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jouer.
        /// </summary>
        public static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Joueurs.
        /// </summary>
        public static string players {
            get {
                return ResourceManager.GetString("players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoyer.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commencer une nouvelle partie.
        /// </summary>
        public static string start_new_serie {
            get {
                return ResourceManager.GetString("start_new_serie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Démarrer la partie.
        /// </summary>
        public static string start_the_game {
            get {
                return ResourceManager.GetString("start_the_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le célèbre jeu de mémoire !.
        /// </summary>
        public static string the_famous_game_of_little_goat {
            get {
                return ResourceManager.GetString("the_famous_game_of_little_goat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour commencer.
        /// </summary>
        public static string to_start {
            get {
                return ResourceManager.GetString("to_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tapez votre message ici.
        /// </summary>
        public static string type_message_here {
            get {
                return ResourceManager.GetString("type_message_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à URL à partager.
        /// </summary>
        public static string url_to_share {
            get {
                return ResourceManager.GetString("url_to_share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider.
        /// </summary>
        public static string validate {
            get {
                return ResourceManager.GetString("validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous ne pouvez pas jouer seul·e !.
        /// </summary>
        public static string you_cant_play_alone {
            get {
                return ResourceManager.GetString("you_cant_play_alone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous ne pouvez lancer la partie, seul le créateur peut.
        /// </summary>
        public static string you_cant_start_the_game_only_creator {
            get {
                return ResourceManager.GetString("you_cant_start_the_game_only_creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre email.
        /// </summary>
        public static string your_email {
            get {
                return ResourceManager.GetString("your_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre nom.
        /// </summary>
        public static string your_name {
            get {
                return ResourceManager.GetString("your_name", resourceCulture);
            }
        }
    }
}
