//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleGoat {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LittleGoat.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue.
        /// </summary>
        public static string an_error_occured {
            get {
                return ResourceManager.GetString("an_error_occured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string chat {
            get {
                return ResourceManager.GetString("chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez un nom.
        /// </summary>
        public static string choose_name {
            get {
                return ResourceManager.GetString("choose_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquez ici pour voir tout l&apos;historique des messages.
        /// </summary>
        public static string click_to_see_older_messages {
            get {
                return ResourceManager.GetString("click_to_see_older_messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copier.
        /// </summary>
        public static string copy_to_clipboard {
            get {
                return ResourceManager.GetString("copy_to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créez une partie en cliquant sur le bouton ci-dessous, copiez-collez ensuite le lien et envoyez-le à vos ami·es !.
        /// </summary>
        public static string create_a_game_message {
            get {
                return ResourceManager.GetString("create_a_game_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer une partie.
        /// </summary>
        public static string create_game {
            get {
                return ResourceManager.GetString("create_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cet email est déjà utilisé. S&apos;il s&apos;agit du votre, n&apos;hésitez pas à utiliser la fonction de récupération de compte..
        /// </summary>
        public static string email_already_used {
            get {
                return ResourceManager.GetString("email_already_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;email n&apos;est pas obligatoire, mais il servira si jamais vous changez de téléphone/PC, pour retrouver votre nom et vos scores.
        /// </summary>
        public static string email_not_mandatory {
            get {
                return ResourceManager.GetString("email_not_mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En jeu.
        /// </summary>
        public static string in_game {
            get {
                return ResourceManager.GetString("in_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cet email n&apos;est pas valide.
        /// </summary>
        public static string invalid_email {
            get {
                return ResourceManager.GetString("invalid_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprendre la dernière partie.
        /// </summary>
        public static string join_last_game {
            get {
                return ResourceManager.GetString("join_last_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biquette.
        /// </summary>
        public static string little_goat {
            get {
                return ResourceManager.GetString("little_goat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mémorisez vos cartes !.
        /// </summary>
        public static string memorize_your_cards {
            get {
                return ResourceManager.GetString("memorize_your_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce nom est déjà utilisé.
        /// </summary>
        public static string name_already_used {
            get {
                return ResourceManager.GetString("name_already_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre nom ne doit pas être vide.
        /// </summary>
        public static string name_cant_be_empty {
            get {
                return ResourceManager.GetString("name_cant_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} de jouer !.
        /// </summary>
        public static string next_to_play_1 {
            get {
                return ResourceManager.GetString("next_to_play_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas d&apos;autres joueurs pour le moment....
        /// </summary>
        public static string no_other_players_yet {
            get {
                return ResourceManager.GetString("no_other_players_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jouer.
        /// </summary>
        public static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joueurs.
        /// </summary>
        public static string players {
            get {
                return ResourceManager.GetString("players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyer.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commencer une nouvelle partie.
        /// </summary>
        public static string start_new_serie {
            get {
                return ResourceManager.GetString("start_new_serie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Démarrer la partie.
        /// </summary>
        public static string start_the_game {
            get {
                return ResourceManager.GetString("start_the_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le célèbre jeu de mémoire !.
        /// </summary>
        public static string the_famous_game_of_little_goat {
            get {
                return ResourceManager.GetString("the_famous_game_of_little_goat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour commencer.
        /// </summary>
        public static string to_start {
            get {
                return ResourceManager.GetString("to_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tapez votre message ici.
        /// </summary>
        public static string type_message_here {
            get {
                return ResourceManager.GetString("type_message_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL à partager.
        /// </summary>
        public static string url_to_share {
            get {
                return ResourceManager.GetString("url_to_share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider.
        /// </summary>
        public static string validate {
            get {
                return ResourceManager.GetString("validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous ne pouvez pas jouer seul·e !.
        /// </summary>
        public static string you_cant_play_alone {
            get {
                return ResourceManager.GetString("you_cant_play_alone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous ne pouvez lancer la partie, seul le créateur peut.
        /// </summary>
        public static string you_cant_start_the_game_only_creator {
            get {
                return ResourceManager.GetString("you_cant_start_the_game_only_creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre email.
        /// </summary>
        public static string your_email {
            get {
                return ResourceManager.GetString("your_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre nom.
        /// </summary>
        public static string your_name {
            get {
                return ResourceManager.GetString("your_name", resourceCulture);
            }
        }
    }
}
