//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleGoat.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerieChat
    {
        public int Id { get; set; }
        public string SerieId { get; set; }
        public string PlayerId { get; set; }
        public string Message { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Serie Serie { get; set; }
    }
}
